<?

$encabeza="Para este año el servicio de transporte será prestado por la Empresa, Cooperativa Multiactiva de Transporte Especial y Turismo ROYAL EXPRESS y los pagos correspondientes se harán directamente a la misma, si usted esta interesado en utilizar este servicio, por favor llene la siguiente solicitud.";

// $inicio ="El valor del presente contrato será cancelado en 10 cuotas mensuales, se tendrá un descuento por pago anual del 2%.";

$punto1="La empresa transporte se obliga a transportar a los estudiantes en el horario establecido por las directivas del colegio. Los horarios para recoger y dejar los estudiantes se estipulan de acuerdo al reconocimiento de ruta según el sector y la hora de cada recorrido.";

$punto2="Durante la emergencia sanitaria, la empresa realizará desinfección de los vehículos antes y después de cada recorrido. Garantizará que los conductores y auxiliares esten preparados con todas las medidas de bioseguridad, tapabocas, guantes, implementos de aseo y desinfección.";

$punto3="El pago de la mensualidad se realizará dentro de los cinco (5) primeros días de cada mes, si hasta el sexto (6) día no se ha cancelado el transporte del estudiante, la empresa no lo transportará y el padre de familia se hará responsable del traslado de su hijo (a) al colegio; sin perjuicio del pago completo del mes respectivo. (El banco, el número de cuenta y el codigo para pago; serán suministrados por la empresa). El servicio de transporte para Sector Rural Metropolitano de Pereira y Dosquebradas se analizará de acuerdo a la ubicación del predio y la firma de esta solicitud no obliga a la empresa a transportar el estudiante. Para el transporte escolar en la modalidad de alternancia, se estableció los siguientes valores según estos porcentajes, si el estudiante va entre 2 a 3 días en la semana deberá cancelar el 75% de la tarifa plena y si va entre 4 a 5 días deberá cancelar el 100% de la tarifa plena.";

$punto4="La empresa no se hace responsable por dineros que no sean consignados directamente en la cuenta correspondiente o entregados al conductor.";

$punto5="Ni la empresa, ni el colegio se hacen responsables de los estudiantes que utilicen otro servicio de transporte particular, diferente al avalado por el colegio.";

$punto6="La empresa de acuerdo al reconocimiento de ruta, diseñara las mismas con la finalidad de prestar un servicio de transporte oportuno, seguro y eficiente, donde evaluará la prestacióon del servicio según la ubicación o vivienda de los estudiantes. Por esto, el estudiante debe tomar y dejar el transporte en el mismo sitio, puerta de la casa o entrada de la urbanización. Para solicitar permiso o cambios de dirección, el padre de familia deberá notificar inmediatamente al Colegio y al Coordinador de transporte de la empresa. Dicha solicitud será por escrito firmada por los padres y entregada al colegio. Los cambios de dirección estarán sujetos a la disponibilidad de cupos en la nueva ruta y se le informara si hay un incremento en la mensualidad, que será prorrateada según la fecha de la solicitud.";

$punto7="Durante la prestación del servicio, el estudiante durante todo el recorrido, debe usar el tapabocas y permanecer sentado en el sitio asignado, utilizando el cinturón de seguridad. Previo al abordaje del vehículo deberá permitir la toma de temperatura y haber diligenciado su estado de salud en la plataforma CHEQUEÁTEAPP";

$punto8="Si el estudiante presenta síntomas relacionados al COVID-19 no podrá utilizar el servicio de transporte, generando incapacidades o ausencias, no eximen a los estudiantes para el no pago del transporte completo durante el mes; puesto que el cupo se le conservará en la respectiva ruta. Esto mismo aplica para viajes o retiros temporales.";

$punto9="La empresa se compromete a cumplir con las normas que el Ministerio de Transporte, Educación y de Salud determine para este tipo de servicio.";

$punto10="Si fuese el caso de suspender el contrato por notificación de parte de las instituciones relacionadas a la emergencia sanitaria, el contrato será suspendido y retomado en la fecha que sea asignada, solo cobrando los servicios utilizados.";

$punto11="Terminación de la solicitud del servicio. Las partes podrán dar por terminado esta solicitud en cualquier momento, preavisando por escrito a la otra parte con 15 días de anticipación a la terminación: En los meses de junio y octubre no se acepta la cancelación de dicho contrato. El contrato de transporte es calculado por los gastos y costes del año y divido en los meses de calendario académico.";

$punto12="Con la firma del presente contrato de Transporte, el Padre de Familia y/o Acudiente se compromete a tomar este servicio de transporte por NUEVE (9) meses, de febrero a octubre y a partir de este momento queda confirmado el contrato de transporte entre el padre de familia y la empresa transportadora. Es de aclarar que si el estudiante debe asistir a refuerzo el mes de noviembre, el padre deberá cancelar el servicio adicional";

$punto13="El presente contrato este sujeto a las condiciones y vigencia del contrato firmado entre ROYAL EXPRESS Y EL COLEGIO, según requerimientos de la DIAN, la empresa se encuentra en la obligación de reportar los pagos que realizan los padres de familia. Por lo anterior, la persona que firme el presente contrato será quien se reporte a la DIAN.";

$punto14="Con la firma del presente contrato, autorizo (mos) a la COOPERATIVA MULTIACTIVA DE TRANSPORTES ESPECIALES Y TURISMO ROYAL EXPRESS, para que haga uso de los datos suministrados en el mismo, en consideración de conformidad con lo establecido en la Ley 1581 de 2012 y el Decreto de Reglamentario 1377 de 2013, normas por medio de las cuales se dictan disposiciones para la proteccion de datos personales en concordancia con la política de tratamiento de datos establecida por la COOPERATIVA MULTIACTIVA DE TRANSPORTES ESPECIALES Y TURISMO ROYAL EXPRESS, puede ser consultada en las oficinas principales en el momento en que se ha requerido.";

$punto15="En ejercicio de mi derecho a la libertad y autodeterminación informática, AUTORIZO de manera expresa, concreta, suficiente, voluntaria, informada e irrevocable a la COOPERATIVA MULTIACTIVA DE TRANSPORTES ESPECIALES Y TURISMO ROYAL EXPRESS, o a quien represente sus derechos u ostente en el futuro a cualquier título de calidad de acreedor a: capturar, tratar, procesar, operar, verificar, transmitir, transferir, usar, poner en circulación, consular, divulgar, reportar y solicitar toda la información que se refiere a nuestro comportamiento crediticio, financiero, comercial y de servicios de los cuales somos sus titulares, referida al nacimiento, ejecución y extinción de obligaciones dinerarias (independientemente de la naturaleza del contrato que les de origen) a nuestro comportamiento e historial crediticio, incluida la información positiva y negativa de mis hábitos de pago y aquella que se refiera a la información personal necesaria para el estudio, análisis y eventual otorgamiento de un crédito o celebración de un contrato, para que dicha información en las bases de datos será determinada por el ordenamiento";

$punto16="El presente contrato esta sujeto a las condiciones y vigencia del contrato firmado entre ROYAL TOUR PLUS S.A.S Y EL COLEGIO, según requerimientos de la DIAN, la empresa se encuentra en la obligación de reportar los pagos que realizan los padres de familia. Por lo anterior, la persona que firme el presente contrato será quien se reporte a la DIAN.";

$punto17="Con la firma del presente contrato, autorizo (mos) a ROYAL TOUR PLUS S.A.S, para que haga uso de los datos suministrados en el mismo, en consideración de conformidad con lo establecido en la Ley 1581 de 2012 y el Decreto de Reglamentario 1377 de 2013, normas por medio de las cuales se dictan disposiciones para la protección de datos personales en concordancia con la política de tratamiento de datos establecida por ROYAL TOUR PLUS S.A.S, puede ser consultada en las oficinas principales en el momento en que se ha requerido.";

$punto18="En ejercicio de mi derecho a la libertad y autodeterminación informática, AUTORIZO de manera expresa, concreta, suficiente, voluntaria, informada e irrevocable a ROYAL TOUR PLUS S.A.S, o a quien represente sus derechos u ostente en el futuro a cualquier titulo de calidad de acreedor a: capturar, tratar, procesar, operar, verificar, transmitir, transferir, usar, poner en circulación, consular, divulgar, reportar y solicitar toda la información que se refiere a nuestro comportamiento crediticio, financiero, comercial y de servicios de los cuales somos sus titulares, referida al nacimiento, ejecución y extinción de obligaciones dinerarias (independientemente de la naturaleza del contrato que les de origen) a nuestro comportamiento e historial crediticio, incluida la información positiva y negativa de mis hábitos de pago y aquella que se refiera a la información personal necesaria para el estudio, análisis y eventual otorgamiento de un crédito o celebración de un contrato, para que dicha información en las bases de datos será determinada por el ordenamiento";

$titulopro="AVISO DE PRIVACIDAD Y AUTORIZACIÓN EXPRESA PARA EL TRATAMIENTO DE DATOS PERSONALES";

$tproteccion="ROYAL TOUR PLUS S.A.S en cumplimiento de lo definido en la ley 1581 de 2012, el decreto reglamentario 1377 de 2013 y nuestra política de protección de datos personales, le informa que los datos que usted suministre en virtud de la relación existente con la sociedad, serán tratados mediante el uso y mantenimiento de medidas de seguridad técnicas, físicas y administrativas a fin de impedir que terceros no autorizados accedan a los mismos, lo anterior de conformidad con lo definido en la ley y el desarrollo de las actividades propias de la cooperativa.
El responsable de tratamiento de sus datos personales es ROYAL TOUR PLUS S.A.S domiciliado y ubicado en la Calle 16 #14-02 Edificio 14Bis oficina 1A de la ciudad de Pereira quien los recogerá a través del personal encargado que se disponga para tales efectos y serán usados para: a) Contar con sus datos personales básicos en el archivo interno. b) Realizar encuestas, estadísticas, invitaciones a convocatorias. c) Atender o formalizar cualquier tipo de trámite, producto o servicio que usted solicite o requiera. d) Poder establecer comunicación en el evento en que sea requerido por autoridad judicial, centro de conciliación, entidad estatal, por asuntos relacionados con los labores desempeñadas en la empresa.
Usted podrá ejercer los derechos que la ley prevé, así como acceder, corregir, actualizar, o suprimir datos, siguiendo el procedimiento que a continuación se describe:";

$texto1="Usted deberá realizar una solicitud sencilla de manera escrita que deberá ser presentada ante las instalaciones de la empresa, en la que se especifique el tramite que desea realizar.";

$texto2="ROYAL TOUR PLUS S.A.S dará trámite a la solicitud en los términos señalados en el MANUAL DE POLÍTICAS Y PROCEDIMIENTOS PARA LA PROTECCIÓN DE DATOS PERSONALES DE ROYAL TOUR PLUS S.A.S.";

$fin="Usted puede conocer nuestro manual de Políticas y protección de datos personales publicados en la sede administrativa.
Es importante mencionar que el ejercicio de sus derechos no es requisito previo ni impide el ejercicio de otro derecho y que cualquier modificación al presente aviso le será notificado a través de los medios que disponga ROYAL TOUR PLUS S.A.S.
Leído lo anterior autorizo de manera previa, explicita e inequívoca a ROYAL TOUR PLUS S.A.S para el tratamiento de los datos personales suministrados por mi persona dentro de las finalidades legales, contractuales, comerciales y las aquí contempladas. Declaro que soy titular de la información reportada en este formulario para autorizar el tratamiento de mis datos personales, que la he suministrado de forma voluntaria y es completa, confiable, veraz, exacta y verídica.";

?>